package com.mule_travel.travelagent;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-05-24T10:33:10.709-03:00
 * Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://www.mule-travel.com/TravelAgent/", name = "TravelAgentService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface TravelAgentService {

    @WebResult(name = "TravelResponse", targetNamespace = "http://www.mule-travel.com/TravelAgent/", partName = "travelResponse")
    @WebMethod(action = "http://www.mule-travel.com/TravelAgent/bookTrip")
    public TravelResponse bookTrip(
        @WebParam(partName = "travelRequest", name = "TravelRequest", targetNamespace = "http://www.mule-travel.com/TravelAgent/")
        TravelRequest travelRequest
    );
}
