package com.mule_air.airline;

import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

import org.springframework.core.io.Resource;
import org.springframework.core.io.support.PathMatchingResourcePatternResolver;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-05-24T10:33:11.208-03:00
 * Generated source version: 2.5.2
 * 
 */
@WebServiceClient(name = "AirlineService", 
                  targetNamespace = "http://www.mule-air.com/Airline/") 
public class AirlineService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.mule-air.com/Airline/", "AirlineService");
    public final static QName AirlineSOAP = new QName("http://www.mule-air.com/Airline/", "AirlineSOAP");
    static {
        URL url = null;
        try {
			Resource[] resources = new PathMatchingResourcePatternResolver().getResources("classpath:/AirlineService.wsdl");
			if (resources.length > 0) {
				url = resources[0].getURL();
			}
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
        WSDL_LOCATION = url;
    }

    public AirlineService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AirlineService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AirlineService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns AirlineService
     */
    @WebEndpoint(name = "AirlineSOAP")
    public AirlineService getAirlineSOAP() {
        return super.getPort(AirlineSOAP, AirlineService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AirlineService
     */
    @WebEndpoint(name = "AirlineSOAP")
    public AirlineService getAirlineSOAP(WebServiceFeature... features) {
        return super.getPort(AirlineSOAP, AirlineService.class, features);
    }

}
