package com.mule_hotel.hotelservice;

import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

import org.springframework.core.io.Resource;
import org.springframework.core.io.support.PathMatchingResourcePatternResolver;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-05-24T10:33:10.929-03:00
 * Generated source version: 2.5.2
 * 
 */
@WebServiceClient(name = "HotelService", 
                  targetNamespace = "http://www.mule-hotel.com/HotelService/") 
public class HotelService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.mule-hotel.com/HotelService/", "HotelService");
    public final static QName HotelServiceSOAP = new QName("http://www.mule-hotel.com/HotelService/", "HotelServiceSOAP");
    static {
        URL url = null;
        try {
			Resource[] resources = new PathMatchingResourcePatternResolver().getResources("classpath:/HotelService.wsdl");
			if (resources.length > 0) {
				url = resources[0].getURL();
			}
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
        WSDL_LOCATION = url;
    }

    public HotelService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HotelService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HotelService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns HotelService
     */
    @WebEndpoint(name = "HotelServiceSOAP")
    public HotelService getHotelServiceSOAP() {
        return super.getPort(HotelServiceSOAP, HotelService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HotelService
     */
    @WebEndpoint(name = "HotelServiceSOAP")
    public HotelService getHotelServiceSOAP(WebServiceFeature... features) {
        return super.getPort(HotelServiceSOAP, HotelService.class, features);
    }

}
