package com.mule_credit.creditcardservice;

import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

import org.springframework.core.io.Resource;
import org.springframework.core.io.support.PathMatchingResourcePatternResolver;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-05-24T10:33:11.059-03:00
 * Generated source version: 2.5.2
 * 
 */
@WebServiceClient(name = "CreditCardService", 
                  targetNamespace = "http://www.mule-credit.com/CreditCardService/") 
public class CreditCardService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.mule-credit.com/CreditCardService/", "CreditCardService");
    public final static QName CreditCardServiceSOAP = new QName("http://www.mule-credit.com/CreditCardService/", "CreditCardServiceSOAP");
    static {
        URL url = null;
        try {
			Resource[] resources = new PathMatchingResourcePatternResolver().getResources("classpath:/CreditCardService.wsdl");
			if (resources.length > 0) {
				url = resources[0].getURL();
			}
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
        WSDL_LOCATION = url;
    }

    public CreditCardService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CreditCardService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CreditCardService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns CreditCardService
     */
    @WebEndpoint(name = "CreditCardServiceSOAP")
    public CreditCardService getCreditCardServiceSOAP() {
        return super.getPort(CreditCardServiceSOAP, CreditCardService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CreditCardService
     */
    @WebEndpoint(name = "CreditCardServiceSOAP")
    public CreditCardService getCreditCardServiceSOAP(WebServiceFeature... features) {
        return super.getPort(CreditCardServiceSOAP, CreditCardService.class, features);
    }

}
