package com.mule_credit.creditcardservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-05-24T10:33:11.050-03:00
 * Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://www.mule-credit.com/CreditCardService/", name = "CreditCardService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CreditCardService {

    @WebResult(name = "PaymentResponse", targetNamespace = "http://www.mule-credit.com/CreditCardService/", partName = "parameters")
    @WebMethod(action = "http://www.mule-credit.com/CreditCardService/authorisePayment")
    public PaymentResponse authorisePayment(
        @WebParam(partName = "parameters", name = "PaymentRequest", targetNamespace = "http://www.mule-credit.com/CreditCardService/")
        PaymentRequest parameters
    );

    @WebResult(name = "CancelationResponse", targetNamespace = "http://www.mule-credit.com/CreditCardService/", partName = "parameters")
    @WebMethod(action = "http://www.mule-credit.com/CreditCardService/cancelPayment")
    public CancelationResponse cancelPayment(
        @WebParam(partName = "parameters", name = "CancelationRequest", targetNamespace = "http://www.mule-credit.com/CreditCardService/")
        CancelationRequest parameters
    );
}
