package com.mule_credit.creditcardservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-05-23T15:09:13.879-03:00
 * Generated source version: 2.5.2
 * 
 */
@WebServiceClient(name = "CreditCardService", 
                  wsdlLocation = "file:/Users/nialdarbey/eclipse_projects/travel-reservation/src/main/resources/CreditCardService.wsdl",
                  targetNamespace = "http://www.mule-credit.com/CreditCardService/") 
public class CreditCardService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.mule-credit.com/CreditCardService/", "CreditCardService");
    public final static QName CreditCardServiceSOAP = new QName("http://www.mule-credit.com/CreditCardService/", "CreditCardServiceSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/nialdarbey/eclipse_projects/travel-reservation/src/main/resources/CreditCardService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CreditCardService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/Users/nialdarbey/eclipse_projects/travel-reservation/src/main/resources/CreditCardService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CreditCardService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CreditCardService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CreditCardService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns CreditCardService
     */
    @WebEndpoint(name = "CreditCardServiceSOAP")
    public CreditCardService getCreditCardServiceSOAP() {
        return super.getPort(CreditCardServiceSOAP, CreditCardService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CreditCardService
     */
    @WebEndpoint(name = "CreditCardServiceSOAP")
    public CreditCardService getCreditCardServiceSOAP(WebServiceFeature... features) {
        return super.getPort(CreditCardServiceSOAP, CreditCardService.class, features);
    }

}
