package com.mule_hotel.hotelservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-05-23T15:09:13.755-03:00
 * Generated source version: 2.5.2
 * 
 */
@WebServiceClient(name = "HotelService", 
                  wsdlLocation = "file:/Users/nialdarbey/eclipse_projects/travel-reservation/src/main/resources/HotelService.wsdl",
                  targetNamespace = "http://www.mule-hotel.com/HotelService/") 
public class HotelService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.mule-hotel.com/HotelService/", "HotelService");
    public final static QName HotelServiceSOAP = new QName("http://www.mule-hotel.com/HotelService/", "HotelServiceSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/nialdarbey/eclipse_projects/travel-reservation/src/main/resources/HotelService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(HotelService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/Users/nialdarbey/eclipse_projects/travel-reservation/src/main/resources/HotelService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public HotelService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HotelService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HotelService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns HotelService
     */
    @WebEndpoint(name = "HotelServiceSOAP")
    public HotelService getHotelServiceSOAP() {
        return super.getPort(HotelServiceSOAP, HotelService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HotelService
     */
    @WebEndpoint(name = "HotelServiceSOAP")
    public HotelService getHotelServiceSOAP(WebServiceFeature... features) {
        return super.getPort(HotelServiceSOAP, HotelService.class, features);
    }

}
