package com.mule_air.airline;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-05-23T15:09:14.016-03:00
 * Generated source version: 2.5.2
 * 
 */
@WebServiceClient(name = "AirlineService", 
                  wsdlLocation = "file:/Users/nialdarbey/eclipse_projects/travel-reservation/src/main/resources/AirlineService.wsdl",
                  targetNamespace = "http://www.mule-air.com/Airline/") 
public class AirlineService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.mule-air.com/Airline/", "AirlineService");
    public final static QName AirlineSOAP = new QName("http://www.mule-air.com/Airline/", "AirlineSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/nialdarbey/eclipse_projects/travel-reservation/src/main/resources/AirlineService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AirlineService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/Users/nialdarbey/eclipse_projects/travel-reservation/src/main/resources/AirlineService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AirlineService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AirlineService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AirlineService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns AirlineService
     */
    @WebEndpoint(name = "AirlineSOAP")
    public AirlineService getAirlineSOAP() {
        return super.getPort(AirlineSOAP, AirlineService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AirlineService
     */
    @WebEndpoint(name = "AirlineSOAP")
    public AirlineService getAirlineSOAP(WebServiceFeature... features) {
        return super.getPort(AirlineSOAP, AirlineService.class, features);
    }

}
