package com.mule_air.airline;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2012-05-23T15:09:14.008-03:00
 * Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://www.mule-air.com/Airline/", name = "AirlineService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface AirlineService {

    @WebResult(name = "FlightReservationResponse", targetNamespace = "http://www.mule-air.com/Airline/", partName = "parameters")
    @WebMethod(action = "http://www.mule-air.com/Airline/reserveFlight")
    public FlightReservationResponse reserveFlight(
        @WebParam(partName = "flightReservationRequest", name = "FlightReservationRequest", targetNamespace = "http://www.mule-air.com/Airline/")
        FlightReservationRequest flightReservationRequest
    );

    @WebResult(name = "FlightConfirmationResponse", targetNamespace = "http://www.mule-air.com/Airline/", partName = "parameters")
    @WebMethod(action = "http://www.mule-air.com/Airline/confirmFlight")
    public FlightConfirmationResponse confirmFlight(
        @WebParam(partName = "flightConfirmationRequest", name = "FlightConfirmationRequest", targetNamespace = "http://www.mule-air.com/Airline/")
        FlightConfirmationRequest flightConfirmationRequest
    );
}
